<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyvote_smartvote"
 *
 * Auto generated by Extension Builder 2015-04-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Easyvote Smartvote',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Fabien Udriot',
	'author_email' => 'fabien@omic.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'easyvote' => '',
			'vidi' => '',
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);