<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyvote_smartvote"
 *
 * Auto generated by Extension Builder 2015-04-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Easyvote Smartvote',
	'description' => 'Import data from the Smartvote platform and display questionnaire to the User',
	'category' => 'plugin',
	'author' => 'Fabien Udriot',
	'author_email' => 'fabien@omic.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'vidi' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);