####################
# Question
####################
-
  name: 'List all questions for an election'
  uriPattern: 'questions/{election}'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'Question'
    '@controller': 'QuestionApi'
    '@action':     'list'
  httpMethods: ['GET']

####################
# Save
####################
-
  name: 'Save the state of an object'
  uriPattern: 'state'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'State'
    '@controller': 'StateApi'
    '@action':     'save'
  httpMethods: ['POST']