####################
# Question
####################
-
  name: 'List all questions for an election'
  uriPattern: 'questions/{election}'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'Question'
    '@controller': 'QuestionApi'
    '@action':     'list'
  httpMethods: ['GET']

####################
# Candidate
####################
-
  name: 'List all candidate for an election'
  uriPattern: 'candidates/{election}'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'Candidate'
    '@controller': 'CandidateApi'
    '@action':     'list'
  httpMethods: ['GET']

####################
# Candidate permalink
####################
-
  name: 'Permalink Candidate'
  uriPattern: 'c/{candidate}'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@controller': 'Candidate'
    '@action':     'permalink'
    '@plugin':     'Candidate'
  httpMethods: ['GET']

####################
# Party
####################
-
  name: 'List all parties'
  uriPattern: 'parties/{election}'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'Party'
    '@controller': 'PartyApi'
    '@action':     'list'
  httpMethods: ['GET']

####################
# Save
####################
-
  name: 'Save the state of an object'
  uriPattern: 'state'
  defaults:
    '@package':    'Visol.Easyvote_smartvote'
    '@plugin':     'State'
    '@controller': 'StateApi'
    '@action':     'save'
  httpMethods: ['POST','PUT']